version: "3.9"
services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Functions
      - "5002:5002" # Hosting (Frontend)
      - "9000:9000" # Realtime DB
      - "4000:4000" # Emulator UI (optional)
